---
- name: Ensure dependencies are installed
  become: yes
  apt:
    name:
      - curl
      - vim
      - jq
      - iputils-ping
      - iptables
      - htop
    state: latest # Обновляет версию пакета если он уже установлен и доступна новая версия
    update_cache: true # Обновление кэша перед установкой пакетов
    cache_valid_time: 3600 # Не будет обновлять если недавно обновляли